version: "19"

services:
  percona:
    image: percona:latest
    container_name: percona
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mariadb_password
    secrets:
      - mariadb_root_password
      - mariadb_password
    volumes:
      - db_data:/var/lib/mysql
      - ./percona/my.cnf:/etc/my.cnf
    ports:
      - "${PERCONA_PORT}:5002"
    networks:
      - prestashop-net

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "/run/secrets/redis_password"]
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    networks:
      - prestashop-net
    depends_on:
      - percona

  prestashop:
    image: prestashop/prestashop:8
    container_name: prestashop
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD_FILE: /run/secrets/mariadb_password
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO}
      PS_ERASE_DB: ${PS_ERASE_DB}
      PS_DOMAIN: ${PS_DOMAIN}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
      PS_EMAIL: ${PS_EMAIL}
      PS_PASSWD_FILE: /run/secrets/prestashop_password
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PS_DEV_MODE: ${PS_DEV_MODE}
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      CACHE_SYSTEM: ${CACHE_SYSTEM}
    secrets:
      - mariadb_password
      - prestashop_password
      - redis_password
    ports:
      - "${PRESTASHOP_PORT}:80"
    volumes:
      - prestashop_data:/var/www/html
      - ./prestashop/config/settings.inc.php:/var/www/html/config/settings.inc.php
    depends_on:
      - percona
      - redis
    networks:
      - prestashop-net

secrets:
  mariadb_root_password:
    file: ./secrets/mariadb_root_password.txt
  mariadb_password:
    file: ./secrets/mariadb_password.txt
  prestashop_password:
    file: ./secrets/prestashop_password.txt
  redis_password:
    file: ./secrets/redis_password.txt

volumes:
  db_data:
  redis_data:
  prestashop_data:

networks:
  prestashop-net:
    driver: bridge
